---
title: "Corn_test"
format: html
    embed-resources: true
    toc: true
    theme: cerulean
author: Bishal Gaire and Meghan Stewart 
---

#Loading Data + Libraries
```{r Loading the data}
library(tidyverse)

library(tidyverse)

test <- read_csv("../Data/testing/testing_submission.csv") %>% 
  mutate(site = substr(site, 1,4))
meta  <- read_csv("../Data/testing/testing_meta.csv") %>% 
  mutate(site = substr(site, 1,4))
soil  <- read_csv("../Data/testing/testing_soil.csv") %>% 
  separate(site, into = c("site", "year"), sep = "_") %>% 
  mutate(year = as.numeric(year))


test <- test %>% 
  filter(site %in% meta$site)

test <- test %>% rename_with(tolower)
meta  <- meta  %>% rename_with(tolower)
soil  <- soil  %>% rename_with(tolower)

data_full <- test %>%
  left_join(meta, by = c("site", "year")) %>%
  left_join(soil, by = c("site", "year"))

glimpse(data_full)


test %>% 
  distinct(site)

meta %>% 
  distinct(site
           )
summary(data_full)

(unique(test$yield_mg_ha) == unique(test$yield_mg_ha))

setdiff(meta$site, test$site)

```

#Dropping NA Values 

```{r Drop critical NA missing variables}
data_model <- data_full %>%
  select(-soilph, -om_pct, -soilk_ppm, -soilp_ppm)

glimpse(data_model)


```




```{r Previous crop missing values}
data_model <- data_model %>%
  mutate(previous_crop = replace_na(previous_crop, "Unknown"))

```


```{r Year and site as factors}
data_model <- data_model %>%
  mutate(
    year = as.factor(year),
    site = as.factor(site)
    
  )


glimpse(data_model)
```


#Daymet Data Pull

```{r Daymet weather data}
# Step C: Download daily weather data from Daymet

library(tidyverse)
library(lubridate)
library(daymetr)

# Create unique site-year combinations with coordinates
site_years <- meta %>%
  distinct(site, year, latitude, longitude) %>%
  filter(!is.na(latitude), !is.na(longitude)) %>%
  mutate(year = as.integer(as.character(year)))

# Function to download weather for one site-year
get_daymet_data <- function(site, year, latitude, longitude) {
  d <- download_daymet(
    site = as.character(site),
    lat = latitude,
    lon = longitude,
    start = year,
    end = year,
    internal = TRUE,
    silent = TRUE
  )
  
  df <- d$data
  
  tibble(
    site = site,
    year = year,
    yday = df$yday,
    prcp = df$prcp..mm.day.,
    tmax = df$tmax..deg.c.,
    tmin = df$tmin..deg.c.,
    srad = df$srad..W.m.2.,
    vp = df$vp..Pa.,
    dayl = df$dayl..s.
  )
}

# Loop through all site-years and combine results
#use_csv = T
#if (use_csv) {
 # weather_daily <- read.csv("../Data/weather_daily.csv")
#} else {
weather_daily <- purrr::pmap_dfr(
  site_years,
  function(site, year, latitude, longitude) {
    tryCatch(
      get_daymet_data(site, year, latitude, longitude),
      error = function(e) NULL
    )
  }
)
write.csv(weather_daily, "../Data/weather_daily_test.csv", row.names = F)
#}

```

##Daymet New Variables


```{r New Variables}
weather_features <- weather_daily %>%
  mutate(
    date = as.Date(yday - 1, origin = paste0(year, "-01-01")) + 1,
    month = month(date),
    tmean = (tmax + tmin) / 2,
    gdd10 = pmax(tmean - 10, 0)
  ) %>%
  group_by(site, year) %>%
  summarise(
    total_prcp = sum(prcp, na.rm = TRUE),
    prcp_apr_sep = sum(prcp[month %in% 4:9], na.rm = TRUE),
    prcp_may_jul = sum(prcp[month %in% 5:7], na.rm = TRUE),
    prcp_aug = sum(prcp[month == 8], na.rm = TRUE),
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_tmin = mean(tmin, na.rm = TRUE),
    mean_tmean = mean(tmean, na.rm = TRUE),
    tmean_apr_sep = mean(tmean[month %in% 4:9], na.rm = TRUE),
    tmax_jul = mean(tmax[month == 7], na.rm = TRUE),
    total_gdd10 = sum(gdd10, na.rm = TRUE),
    gdd10_apr_sep = sum(gdd10[month %in% 4:9], na.rm = TRUE),
    mean_srad = mean(srad, na.rm = TRUE),
    mean_vp = mean(vp, na.rm = TRUE),
    mean_dayl = mean(dayl, na.rm = TRUE),
    .groups = "drop"
  )

data_model_weather <- data_model %>%
  mutate(year = as.integer(as.character(year))) %>%
  left_join(weather_features, by = c("site", "year"))

summary(data_model)

```
```{r Glimpse of weather_daily}
glimpse(weather_daily)
```
```{r summary of data_model_weather}
glimpse(data_model_weather)
summary(data_model_weather)
```

```{r checking open data}
final_test <- data_model_weather

colSums(is.na(final_test))

```

```{r Final data formation}
final_test <- data_model_weather %>%
  select(
    yield_mg_ha,
    
    hybrid, site, year, previous_crop,
    
    
    
    
    total_prcp, prcp_apr_sep, prcp_may_jul, prcp_aug,
    mean_tmean, mean_tmax, mean_tmin, tmean_apr_sep, tmax_jul,
    total_gdd10, gdd10_apr_sep,
    mean_srad, mean_vp, mean_dayl
  )

```

#XGBoost Prediction
```{r}
library(tidymodels)
library(xgboost)
library(tidyverse)


```

```{r}
corn_train <- read_csv("../Data/final_data.csv", show_col_types = FALSE) %>%
  select(
    yield_mg_ha,
    hybrid, site, year, previous_crop,
    total_prcp, prcp_apr_sep, prcp_may_jul, prcp_aug,
    mean_tmean, mean_tmax, mean_tmin, tmean_apr_sep, tmax_jul,
    total_gdd10, gdd10_apr_sep,
    mean_srad, mean_vp, mean_dayl
  ) %>%
  mutate(
    hybrid = as.factor(hybrid),
    site = as.factor(site),
    year = as.factor(year),
    previous_crop = as.factor(previous_crop)
  ) %>%
  drop_na()
```
```{r}
# test data: keep same predictor columns as training, except yield
final_test <- final_test %>%
  select(
    yield_mg_ha,
    hybrid, site, year, previous_crop,
    total_prcp, prcp_apr_sep, prcp_may_jul, prcp_aug,
    mean_tmean, mean_tmax, mean_tmin, tmean_apr_sep, tmax_jul,
    total_gdd10, gdd10_apr_sep,
    mean_srad, mean_vp, mean_dayl
  ) %>%
  mutate(
    hybrid = as.factor(hybrid),
    site = as.factor(site),
    year = as.factor(year),
    previous_crop = as.factor(previous_crop)
  )

```


```{r}
corn_recipe <- recipe(yield_mg_ha ~ ., data = corn_train) %>%
  step_novel(all_nominal_predictors()) %>%
  step_unknown(all_nominal_predictors()) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_zv(all_predictors())
```

```{r}
final_corn <- boost_tree(
  trees = 426,
  tree_depth = 6,
  min_n = 10,
  learn_rate = 0.06827874
) %>%
  set_engine("xgboost") %>%
  set_mode("regression")
```


```{r}
final_corn_op <- workflow() %>%
  add_model(final_corn) %>%
  add_recipe(corn_recipe)
```

```{r}
final_corn_trainer <- final_corn_op %>%
  fit(data = corn_train)
```


```{r}
test_pred <- predict(
  final_corn_trainer,
  new_data = final_test %>% select(-yield_mg_ha)
)

head(test_pred)
test_pred
write.csv(test_pred, "../Output/test_pred.csv", row.names = FALSE)
```

```{r checking xgboost covariates}
xgb_vars <- c(
  "hybrid",
  "site",
  "year",
  "previous_crop",
  "total_prcp",
  "prcp_apr_sep",
  "prcp_may_jul",
  "prcp_aug",
  "mean_tmean",
  "mean_tmax",
  "mean_tmin",
  "tmean_apr_sep",
  "tmax_jul",
  "total_gdd10",
  "gdd10_apr_sep",
  "mean_srad",
  "mean_vp",
  "mean_dayl"
)

#complete.cases  employed here for data cleaning so it only selects rows without NA. Only added it because of issues during running the model before this. 
complete_idx <- complete.cases(final_test[, xgb_vars])

table(complete_idx)

colSums(is.na(final_test[, xgb_vars]))
```


```{r xgboost test set predictions}
xgb_preds <- rep(NA_real_, nrow(final_test))

xgb_preds[complete_idx] <- predict(
  final_corn_trainer,
  new_data = final_test[complete_idx, ] %>% select(-yield_mg_ha)
) %>%
  pull(.pred)

final_test$xgb_pred <- xgb_preds
final_test$has_complete_xgb_vars <- complete_idx

summary(final_test$xgb_pred)
head(final_test$xgb_pred)
head(xgb_preds)
```


```{r saving xgboost predictions}
final_corn_xgb <- final_test %>%
  transmute(
    year,
    site,
    hybrid,
    yield_mg_ha = xgb_pred
  )

final_corn_xgb

write_csv(final_corn_xgb, "../Output/testing_submission_XGBoost_preds.csv")
```

```{r}
final_corn_xgb <- final_test %>%
  transmute(
    year,
    site,
    hybrid,
    yield_mg_ha = xgb_pred
  ) %>%
  distinct()

nrow(final_corn_xgb)

write_csv(final_corn_xgb, "../Output/testing_submission_XGBoost_preds.csv")
```

