---
title: "GAM"
format: html
editor: visual
Author: Bishal and Meghan 
---

#Library Load

```{r loading libraries }
library(tidyverse)
library(lubridate)
library(daymetr)
library(tidymodels)
library(mgcv)



```

#Making Test Set

```{r defining test set }
test <- read_csv("../Data/testing/testing_submission_model2.csv") %>%
  mutate(site = substr(site, 1, 4))

meta <- read_csv("../Data/testing/testing_meta.csv") %>%
  mutate(site = substr(site, 1, 4))

soil <- read_csv("../Data/testing/testing_soil.csv") %>%
  separate(site, into = c("site", "year"), sep = "_") %>%
  mutate(year = as.numeric(year))

# keep only test sites that are in meta
test <- test %>%
  filter(site %in% meta$site)

# standardize names to lower case
test <- test %>% rename_with(tolower)
meta <- meta %>% rename_with(tolower)
soil <- soil %>% rename_with(tolower)
```

#Making data_full

```{r making full dataset }

data_full <- test %>%
  left_join(meta, by = c("site", "year")) %>%
 left_join(soil, by = c("site", "year"))

data_model <- data_full %>%
  select(-soilph, -om_pct, -soilk_ppm, -soilp_ppm) %>%
  mutate(
    previous_crop = replace_na(previous_crop, "Unknown"),
    year = as.integer(year),
    site = as.character(site)
  )

```

#Daymet Pull

```{r site-year format for weather pull}

site_years <- meta %>%
  distinct(site, year, latitude, longitude) %>%
  filter(!is.na(latitude), !is.na(longitude)) %>%
  mutate(year = as.integer(as.character(year)))

```

```{r daymet }

get_daymet_data <- function(site, year, latitude, longitude) {
  d <- download_daymet(
    site    = as.character(site),
    lat     = latitude,
    lon     = longitude,
    start   = year,
    end     = year,
    internal = TRUE,
    silent   = TRUE
  )

  df <- d$data

  tibble(
    site = site,
    year = year,
    yday = df$yday,
    prcp = df$prcp..mm.day.,
    tmax = df$tmax..deg.c.,
    tmin = df$tmin..deg.c.,
    srad = df$srad..W.m.2.,
    vp   = df$vp..Pa.,
    dayl = df$dayl..s.
  )
}

weather_daily <- purrr::pmap_dfr(
  site_years,
  function(site, year, latitude, longitude) {
    tryCatch(
      get_daymet_data(site, year, latitude, longitude),
      error = function(e) NULL
    )
  }
)

write.csv(weather_daily, "../Data/weather_daily_test.csv", row.names = FALSE)

```

#Weather Feature Engineering

```{r feature engineering weather }
weather_features <- weather_daily %>%
  mutate(
    date  = as.Date(yday - 1, origin = paste0(year, "-01-01")) + 1,
    month = month(date),
    tmean = (tmax + tmin) / 2,
    gdd10 = pmax(tmean - 10, 0)
  ) %>%
  group_by(site, year) %>%
  summarise(
    total_prcp    = sum(prcp, na.rm = TRUE),
    prcp_apr_sep  = sum(prcp[month %in% 4:9], na.rm = TRUE),
    prcp_may_jul  = sum(prcp[month %in% 5:7], na.rm = TRUE),
    prcp_aug      = sum(prcp[month == 8], na.rm = TRUE),
    mean_tmax     = mean(tmax, na.rm = TRUE),
    mean_tmin     = mean(tmin, na.rm = TRUE),
    mean_tmean    = mean(tmean, na.rm = TRUE),
    tmean_apr_sep = mean(tmean[month %in% 4:9], na.rm = TRUE),
    tmax_jul      = mean(tmax[month == 7], na.rm = TRUE),
    total_gdd10   = sum(gdd10, na.rm = TRUE),
    gdd10_apr_sep = sum(gdd10[month %in% 4:9], na.rm = TRUE),
    mean_srad     = mean(srad, na.rm = TRUE),
    mean_vp       = mean(vp, na.rm = TRUE),
    mean_dayl     = mean(dayl, na.rm = TRUE),
    .groups = "drop"
  )


data_model <- data_model %>%
  mutate(
    site = as.character(site),
    year = as.integer(year)
  )

weather_features <- weather_features %>%
  mutate(
    site = as.character(site),
    year = as.integer(year)
  )

#creating weather proxy data for 2024 to predict on test set
site_weather_means <- weather_features %>%
group_by(site) %>%
summarise(
total_prcp = mean(total_prcp, na.rm = TRUE),
prcp_apr_sep = mean(prcp_apr_sep, na.rm = TRUE),
prcp_may_jul = mean(prcp_may_jul, na.rm = TRUE),
prcp_aug = mean(prcp_aug, na.rm = TRUE),
mean_tmax = mean(mean_tmax, na.rm = TRUE),
mean_tmin = mean(mean_tmin, na.rm = TRUE),
mean_tmean = mean(mean_tmean, na.rm = TRUE),
tmean_apr_sep = mean(tmean_apr_sep, na.rm = TRUE),
tmax_jul = mean(tmax_jul, na.rm = TRUE),
total_gdd10 = mean(total_gdd10, na.rm = TRUE),
gdd10_apr_sep = mean(gdd10_apr_sep, na.rm = TRUE),
mean_srad = mean(mean_srad, na.rm = TRUE),
mean_vp = mean(mean_vp, na.rm = TRUE),
mean_dayl = mean(mean_dayl, na.rm = TRUE),
.groups = "drop"
)

site_weather_means

```

```{r  weather join changing data format}
data_model <- data_model %>%
mutate(
site = as.character(site),
year = as.integer(year),
previous_crop = replace_na(previous_crop, "Unknown")
)

site_weather_means <- site_weather_means %>%
mutate(site = as.character(site))


```

```{r joining data in weather and final test data}
data_model_weather <- data_model %>%
left_join(site_weather_means, by = "site")

#Building here final_test set with GAM predictors needed

final_test <- data_model_weather %>%
select(
yield_mg_ha,
hybrid, site, year, previous_crop,
total_prcp, prcp_apr_sep, prcp_may_jul, prcp_aug,
mean_tmean, mean_tmax, mean_tmin, tmean_apr_sep, tmax_jul,
total_gdd10, gdd10_apr_sep,
mean_srad, mean_vp, mean_dayl
)

#still having NA issues so let's fix that: 
final_test <- final_test %>%
  mutate(
    site          = ifelse(is.na(site), "Unknown_site", site),
    previous_crop = ifelse(is.na(previous_crop), "Unknown_crop", previous_crop)
  )


```

```{r}
colSums(is.na(final_test[, c(
"prcp_apr_sep","prcp_aug","mean_tmean","tmax_jul",
"gdd10_apr_sep","mean_srad","mean_vp"
)]))
```

```{r troubleshooting chunk for NAs}
str(data_model[, c("site","year")])
str(weather_features[, c("site","year")])
```

#Loading corn_train

```{r corn train load-in}

corn_train <- read_csv("../Data/final_data.csv", show_col_types = FALSE) %>%
  select(
    yield_mg_ha,
    hybrid, site, year, previous_crop,
    total_prcp, prcp_apr_sep, prcp_may_jul, prcp_aug,
    mean_tmean, mean_tmax, mean_tmin, tmean_apr_sep, tmax_jul,
    total_gdd10, gdd10_apr_sep,
    mean_srad, mean_vp, mean_dayl
  ) %>%
  mutate(
    site = as.character(site),
    year = as.integer(year),
    previous_crop = replace_na(previous_crop, "Unknown")
  ) %>%
  drop_na()
```

```{r gam_fit defined}
gam_fit <- readRDS("../Data/gam_fit.rds")

mf_train <- gam_fit$model

train_year_levels  <- levels(mf_train$year)            # trying to make levels the same to avoid merge errors with the data
train_site_levels  <- c(levels(mf_train$site), "Unknown_site")
train_site_levels  <- unique(train_site_levels)

# Use 2023 (last training set year) as proxy for 2024: did this because GAM cannot predict on the 2024 test set so I will let it predict based on approximating it from the previous year's conditions. 


proxy_year <- tail(train_year_levels, 1)

# 2. Rebuild year in final_test:
final_test <- final_test %>%
  mutate(
    year_num = as.integer(year),
    year_num = ifelse(year_num == 2024L, as.integer(proxy_year), year_num),
    year_chr = as.character(year_num),
    year     = factor(year_chr, levels = train_year_levels)
  ) %>%
  select(-year_num, -year_chr)



```

```{r test data alignment}
# Align site & previous_crop 
final_test <- final_test %>%
  mutate(
    site          = factor(as.character(site),
                           levels = train_site_levels),
    
  )

#note: we took previous_crop out for training and running model since it was almost all NA for 2024. 

#checking here for remaining NAs
colSums(is.na(final_test[, c(
  "prcp_apr_sep","prcp_aug","mean_tmean","tmax_jul",
  "gdd10_apr_sep","mean_srad","mean_vp",
  "site","year"
)]))
```

```{r checking covariates}
complete_idx <- complete.cases(final_test[, c(
  "prcp_apr_sep","prcp_aug","mean_tmean","tmax_jul",
  "gdd10_apr_sep","mean_srad","mean_vp",
  "site","year"
)])

#again, used this for dropping NA cells from final test set.


table(complete_idx)
```

#Predicting on Test Set

```{r test set predictions}
gam_preds <- rep(NA_real_, nrow(final_test))
gam_preds[complete_idx] <- predict(
  gam_fit,
  newdata = final_test[complete_idx, ],
  type = "response"
)

final_test$gam_pred    <- gam_preds
final_test$has_weather <- complete_idx

summary(final_test$gam_pred)
head(final_test$gam_pred)

head(gam_preds)
```

```{r saving predictions}
final_corn_gam <- final_test %>%
  transmute(
    year,
    site,
    hybrid,
    yield_mg_ha = gam_pred
  )

#used transmute instead of mutate and select like in class because it didn't work for keeping the yield column name in the final csv. 

final_corn_gam
  
write_csv(final_corn_gam, "../Output/testing_submission_GAM_preds.csv")
```
